defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1d927e1e-3c04-4893-ba84-0c3b6f2cbd39 # Home
handle: homePage
maxAuthors: 1
minAuthors: 0
name: 'Home Page'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: 'http://localhost:3000/?token={previewToken}&x-craft-live-preview=1&draftId={draftId}&canonicalId={canonicalId}'
propagationMethod: all
siteSettings:
  252d2f43-ca1a-4f56-8b71-a79814479385: # Nuxt Craft POC
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
