defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 98a91638-923d-4ee9-90da-dfb3b25c8920 # News Category
handle: newsCategories
maxAuthors: 1
minAuthors: 0
name: 'News Categories'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: true
    urlFormat: '$FRONTEND_URL/{uri}'
propagationMethod: all
siteSettings:
  252d2f43-ca1a-4f56-8b71-a79814479385: # Nuxt Craft POC
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'news/category/{slug}'
structure:
  maxLevels: 1
  uid: bf7da7e9-9110-4fe5-9b90-3193c9bf179e
type: structure
