defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b378aa0f-8cb8-4532-8eb6-8a143b395815 # News Article
handle: news
maxAuthors: 1
minAuthors: 0
name: News
previewTargets:
  -
    label: 'Primary entry page'
    refresh: true
    urlFormat: '$FRONTEND_URL/{uri}'
propagationMethod: all
siteSettings:
  252d2f43-ca1a-4f56-8b71-a79814479385: # Nuxt Craft POC
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'news/{slug}'
type: channel
