allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  8ab147a9-c53d-424b-9c64-b7ab91e04834:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-05-27T00:00:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: CraftCms\Cms\FieldLayout\LayoutElements\Entries\EntryTitleField
            uid: 497a8e74-8d87-4908-ac2d-cde25b2a9249
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cdb405f7-eaa6-42b7-b744-71a59a756a80
        userCondition: null
    thumbFieldKey: null
handle: newsCategory
hasTitleField: true
icon: tag
name: 'News Category'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
