query HomePage($canonicalId: QueryArgument, $provisionalDrafts: Boolean) {
    entry(section: "homePage", draftOf: $canonicalId, provisionalDrafts: $provisionalDrafts) {
        ... on home_Entry {
            id
            title
            brow
            subtitle
            heroImage {
                url(handle: "hero")
                alt
                width(handle: "hero")
                height(handle: "hero")
            }
            buttonGroup {
                ... on button_Entry {
                    title
                    variant
                    path {
                        url
                        target
                    }
                }
            }
        }
    }
}
