query Navigation {
    navigationEntries(level: 1) {
        ... on navItem_Entry {
            id
            title
            path {
                url
                target
                label
                element { uri }
            }
            children {
                ... on navItem_Entry {
                    id
                    title
                    path {
                        url
                        target
                        label
                        element { uri }
                    }
                }
            }
        }
    }
}
