query NewsListing($limit: Int, $offset: Int) {
    total: entryCount(section: "news")
    newsEntries(limit: $limit, offset: $offset) {
        ... on newsArticle_Entry {
            id
            title
            slug
            dateCreated
            summary
            heroImage {
                url(width: 400, height: 260, mode: "crop")
                alt
            }
            categories {
                ... on newsCategory_Entry {
                    id
                    title
                    slug
                }
            }
        }
    }
}
